version: 2
updates:
  - directory: /.github/workflows
    package-ecosystem: github-actions
    schedule:
      interval: monthly
    assignees:
      - axelrindle

  - directory: /backend
    package-ecosystem: composer
    schedule:
      interval: monthly
    assignees:
      - axelrindle

  # bun not supported yet: https://github.com/dependabot/dependabot-core/issues/6528
  # - directory: /frontend
  #   package-ecosystem: npm
  #   schedule:
  #     interval: monthly
  #   assignees:
  #     - cwerl
  #     - thomagoi
