import "@/app/globals.css";
import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const locale = await getLocale();
    return (
        <html lang={locale}>
            <body className={inter.className}>
                <main className="mx-5 mt-16 sm:ml-[300px] sm:mt-3">
                    {children}
                </main>
            </body>
        </html>
    );
}
