#!/bin/bash

COMPOSER_BINARY="${HOME}/bin/composer"

function download_composer {
    curl --silent https://api.github.com/repos/composer/composer/releases/latest |\
        jq '.assets[] | select(.name == "composer.phar") | .browser_download_url' -r |\
        wget --quiet -O "${COMPOSER_BINARY}" -i -
}

if [ ! -f "${COMPOSER_BINARY}" ]; then
    download_composer
fi

exec ./php -f "${COMPOSER_BINARY}" -- $@
