format = '''
[┌───────────────────>](bold green) $sudo$username
[│](bold green) $directory$package$git_branch$git_status$git_state
[└─>](bold green) '''

[directory]
truncate_to_repo = false

[username]
show_always = true
format = '[$user]($style)'

[hostname]
format = '[$ssh_symbol$hostname]($style)'
ssh_only = false

[sudo]
disabled = false
format = '[$symbol]($style)'

[python]
disabled = false
