FROM dunglas/frankenphp:php8.3-alpine

RUN install-php-extensions \
        pgsql \
        redis \
        opcache \
        pcntl

COPY . /app

RUN rm -rf frontend && \
    wget https://github.com/composer/composer/releases/download/2.7.6/composer.phar -O composer && \
    php composer install --no-dev && \
    php artisan storage:link && \
    rm composer

VOLUME [ "/app/storage" ]

EXPOSE 8000

CMD [ "php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8000" ]
