name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PHP_VERSION: 8.3

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: xdebug

      - name: Install Composer
        run: |
          wget https://github.com/composer/composer/releases/download/latest/composer.phar -O ./composer
          chmod +x ./composer

      - name: Install dependencies
        run: ./composer install

      - name: Run tests
        run: ./composer run-script test
