name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PHP_VERSION: 8.3

jobs:
  test-backend:
    name: Run Laravel Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: xdebug

      - name: Install Composer
        run: |
          wget https://github.com/composer/composer/releases/latest/download/composer.phar -O ./composer
          chmod +x ./composer

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: ./composer install

      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: vendor
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Run tests
        run: ./composer run-script test

  build-frontend:
    name: Build Next.js app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('frontend/bun.lockb') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile
        working-directory: frontend

      - uses: actions/cache/save@v4
        if: steps.cache.outputs.cache-hit != 'true'
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-${{ hashFiles('frontend/bun.lockb') }}

      - name: Lint
        run: bun run lint
        working-directory: frontend

      - name: Build
        run: bun run build
        working-directory: frontend
