name: Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PLATFORM: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.PLATFORM }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          push: ${{ github.event_name != 'pull_request' && 'always' || 'never' }}
          platform: ${{ env.PLATFORM }}
