name: Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - .devcontainer
  pull_request:
    branches:
      - main
    paths:
      - .devcontainer
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  PLATFORM: linux/amd64,linux/arm64

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORM }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          labels: |
            org.opencontainers.image.title="intranet-devcontainer"
            org.opencontainers.image.vendor="act coding GbR"

      - name: Build and push
        uses: docker/build-push-action@v6
        id: push
        with:
          context: .devcontainer
          file: .devcontainer/Dockerfile
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/devcontainer
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' && !env.ACT }}
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
          platforms: ${{ env.PLATFORM }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        if: github.event_name != 'pull_request' && !env.ACT
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository }}/devcontainer
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
